version: '3'

services:
  npd:
    build:
      context: .
      args:
        - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
        - POETRY_VERSION=${POETRY_VERSION}
        - DEV_IMAGE=${DEV_IMAGE}
    image: georgysk/npd:0.1.3-alpha
    volumes:
      - .:/opt/npd
    stdin_open: true
    tty: true
