from fractions import Fraction

MIN_COORDINATE = 0
MAX_COORDINATE = 2
MAX_DENOMINATOR = 2
MIN_POLYGON_SIZE = 4
MAX_POLYGON_SIZE = 4
MIN_HOLES_SIZE = 0
MAX_HOLES_SIZE = 0
MIN_HOLE_SIZE = 3
MAX_HOLE_SIZE = 3
MIN_REQRUIREMENTS_COUNT = 2
MAX_REQRUIREMENTS_COUNT = 10
MIN_REQUIREMENT_FRACTION = Fraction(1, 10)
MAX_REQUIREMENT_FRACTION = Fraction(1, 2)
# the following values are approximate
MIN_STEINER_POINTS_COUNT = 1
MAX_STEINER_POINTS_COUNT = 4
# MIN_STEINER_POINTS_COUNT = 200
# MAX_STEINER_POINTS_COUNT = 300

# MIN_COORDINATE = -100
# MAX_COORDINATE = 100
# MAX_DENOMINATOR = None
# MIN_POLYGON_SIZE = 3
# MAX_POLYGON_SIZE = 30
# MIN_HOLES_SIZE = 0
# MAX_HOLES_SIZE = 5
# MIN_HOLE_SIZE = 3
# MAX_HOLE_SIZE = 5
# MIN_REQUIREMENT_FRACTION = Fraction(1, 10)
# MAX_REQUIREMENT_FRACTION = Fraction(1, 2)
